//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phi.MobileWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phi.MobileWebApp.App_LocalResources.GlobalResources", typeof(GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О нашей компании.
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О нас.
        /// </summary>
        public static string AboutPage {
            get {
                return ResourceManager.GetString("AboutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для чего одеть эту вещь.
        /// </summary>
        public static string ActionType {
            get {
                return ResourceManager.GetString("ActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лёгкая одежда с активными компонентами охлаждения.
        /// </summary>
        public static string ACTIVE_COOLING {
            get {
                return ResourceManager.GetString("ACTIVE_COOLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очень тёплая согревающая одежда с активными компонентами.
        /// </summary>
        public static string ACTIVE_HEAT {
            get {
                return ResourceManager.GetString("ACTIVE_HEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление вещи.
        /// </summary>
        public static string AddDress {
            get {
                return ResourceManager.GetString("AddDress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительная Информация.
        /// </summary>
        public static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле Дополнительная Информация должно быть не больше 2000..
        /// </summary>
        public static string AdditionalInfoLenghtLimit {
            get {
                return ResourceManager.GetString("AdditionalInfoLenghtLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить и перейти к расширенным настройкам профиля.
        /// </summary>
        public static string AdvancedProfileSettings {
            get {
                return ResourceManager.GetString("AdvancedProfileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возраст.
        /// </summary>
        public static string Ages {
            get {
                return ResourceManager.GetString("Ages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Защита от диких животных.
        /// </summary>
        public static string ANIMALS_PROTECTION {
            get {
                return ResourceManager.GetString("ANIMALS_PROTECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Броня.
        /// </summary>
        public static string Armor {
            get {
                return ResourceManager.GetString("Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бронь (%).
        /// </summary>
        public static string ArmoringPercent {
            get {
                return ResourceManager.GetString("ArmoringPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация через Ваш {0} аккаунт..
        /// </summary>
        public static string AssociateAccountFormat {
            get {
                return ResourceManager.GetString("AssociateAccountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация через внешний аккаунт.
        /// </summary>
        public static string AssociateSocialAccount {
            get {
                return ResourceManager.GetString("AssociateSocialAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма соединения.
        /// </summary>
        public static string AssociationForm {
            get {
                return ResourceManager.GetString("AssociationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аватар.
        /// </summary>
        public static string AvatarPicture {
            get {
                return ResourceManager.GetString("AvatarPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блог.
        /// </summary>
        public static string BlogPage {
            get {
                return ResourceManager.GetString("BlogPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подыскиваем одежду под погоду....
        /// </summary>
        public static string Calculations {
            get {
                return ResourceManager.GetString("Calculations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить пароль.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма изменения пароля.
        /// </summary>
        public static string ChangePasswordForm {
            get {
                return ResourceManager.GetString("ChangePasswordForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для подтверждения регистрации перейдите по ссылке,которую мы отправили на указанный e-mail..
        /// </summary>
        public static string CheckEmailToConfirmRegistration {
            get {
                return ResourceManager.GetString("CheckEmailToConfirmRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы помогаем &lt;i&gt;одеться по погоде&lt;/i&gt; и &lt;i&gt;спланировать гардероб&lt;/i&gt; для путешествия, а также &lt;i&gt;заранее предупреждаем о сюпризах природы&lt;/i&gt;..
        /// </summary>
        public static string CleverWearerDescription {
            get {
                return ResourceManager.GetString("CleverWearerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string CleverWearerEnterHeader {
            get {
                return ResourceManager.GetString("CleverWearerEnterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Подсказываем какую одежду из вашего гардероба лучше одеть в такую погоду&lt;br&gt;
        ///- Подсказываем где можно приобрести одежду в вашем городе&lt;br&gt;
        ///- Сообщаем по E-mail о резких изменениях погоды&lt;br&gt;
        ///- Подсказываем что взять с собой в путешествие или командировку в любое место на Земле.
        /// </summary>
        public static string CleverWearerFunctions {
            get {
                return ResourceManager.GetString("CleverWearerFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что у нас есть для вас?.
        /// </summary>
        public static string CleverWearerFunctionsHeader {
            get {
                return ResourceManager.GetString("CleverWearerFunctionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что ЕЩЁ у нас скоро появится?.
        /// </summary>
        public static string CleverWearerFutureFunctionsHeader {
            get {
                return ResourceManager.GetString("CleverWearerFutureFunctionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деньги?.
        /// </summary>
        public static string CleverWearerMoney {
            get {
                return ResourceManager.GetString("CleverWearerMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to кликните ссылку для входа.
        /// </summary>
        public static string ClickToLogin {
            get {
                return ResourceManager.GetString("ClickToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Планета Земля&lt;br /&gt;
        ///Солнечная система&lt;br /&gt;
        ///Рука Ориона&lt;br /&gt;
        ///Млечный путь&lt;br /&gt;
        ///Суперкластер Вирго&lt;br /&gt;
        ///Вселенная.
        /// </summary>
        public static string CompanyAddress {
            get {
                return ResourceManager.GetString("CompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФИО Директора.
        /// </summary>
        public static string CompanyCEO {
            get {
                return ResourceManager.GetString("CompanyCEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле ФИО Директора должно быть не больше 255..
        /// </summary>
        public static string CompanyCEOLenghtLimit {
            get {
                return ResourceManager.GetString("CompanyCEOLenghtLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string CompanyEmail {
            get {
                return ResourceManager.GetString("CompanyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле Email должно быть не больше 255..
        /// </summary>
        public static string CompanyEmailLenghtLimit {
            get {
                return ResourceManager.GetString("CompanyEmailLenghtLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факс.
        /// </summary>
        public static string CompanyFax {
            get {
                return ResourceManager.GetString("CompanyFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле Факс должно быть не больше 50..
        /// </summary>
        public static string CompanyFaxLenghtLimit {
            get {
                return ResourceManager.GetString("CompanyFaxLenghtLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название Организации.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле Название Организации должно быть не больше 255..
        /// </summary>
        public static string CompanyNameLenghtLimit {
            get {
                return ResourceManager.GetString("CompanyNameLenghtLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string CompanyPhone {
            get {
                return ResourceManager.GetString("CompanyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле Телефон должно быть не больше 50..
        /// </summary>
        public static string CompanyPhoneLenghtLimit {
            get {
                return ResourceManager.GetString("CompanyPhoneLenghtLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт подтверждён.
        /// </summary>
        public static string ConfirmAccount {
            get {
                return ResourceManager.GetString("ConfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить e-mail не удалось..
        /// </summary>
        public static string ConfirmEmailFailed {
            get {
                return ResourceManager.GetString("ConfirmEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторите пароль.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторите пароль.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите свою регистрацию.
        /// </summary>
        public static string ConfirmRegistrationHeader {
            get {
                return ResourceManager.GetString("ConfirmRegistrationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите свою регистрацию.
        /// </summary>
        public static string ConfirmYourAccount {
            get {
                return ResourceManager.GetString("ConfirmYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;table width=&quot;100%&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; style=&quot;background-color: #ffffff;&quot;&gt;
        ///			&lt;tbody&gt;
        ///				&lt;tr&gt;
        ///					&lt;td style=&quot;padding: 0px;&quot;&gt;
        ///					&lt;table width=&quot;700&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; align=&quot;center&quot; style=&quot;background-color: #eaeaea; table-layout: fixed;&quot;&gt;
        ///						&lt;tbody&gt;
        ///							&lt;tr&gt;
        ///								&lt;td&gt;
        ///								&lt;table width=&quot;700&quot; height=&quot;100&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; bord [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ConfirmYourAccountContent {
            get {
                return ResourceManager.GetString("ConfirmYourAccountContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приветствуем Вас! Вы только что создали аккаунт в Clever Weather. Пожалуйста, подтвердите свой e-mail перейдя по ссылке: {0}. С любым вопросами и пожеланиями можете обращаться прямо в ответе на этот e-mail или по адресу {1}..
        /// </summary>
        public static string ConfirmYourAccountContentPlainText {
            get {
                return ResourceManager.GetString("ConfirmYourAccountContentPlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наши контакты.
        /// </summary>
        public static string ContactDescription {
            get {
                return ResourceManager.GetString("ContactDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        public static string ContactPage {
            get {
                return ResourceManager.GetString("ContactPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать пару логин-пароль.
        /// </summary>
        public static string CreateLocalLogin {
            get {
                return ResourceManager.GetString("CreateLocalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать лук.
        /// </summary>
        public static string CreateLook {
            get {
                return ResourceManager.GetString("CreateLook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru.
        /// </summary>
        public static string CurrentLang {
            get {
                return ResourceManager.GetString("CurrentLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий пароль.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если вам понравился наш сайт вы можете помочь нам улучшить его отправив нам любую сумму на .
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для рекомендаций нам нужен хотя бы один город.
        /// </summary>
        public static string DontDeleteCity {
            get {
                return ResourceManager.GetString("DontDeleteCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрируйтесь.
        /// </summary>
        public static string DoRegister {
            get {
                return ResourceManager.GetString("DoRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войдите.
        /// </summary>
        public static string DoSignIn {
            get {
                return ResourceManager.GetString("DoSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гардероб.
        /// </summary>
        public static string DressingRoom {
            get {
                return ResourceManager.GetString("DressingRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гардероб.
        /// </summary>
        public static string DressRoom {
            get {
                return ResourceManager.GetString("DressRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование вещи.
        /// </summary>
        public static string EditDress {
            get {
                return ResourceManager.GetString("EditDress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Править гардероб.
        /// </summary>
        public static string EditWardrobe {
            get {
                return ResourceManager.GetString("EditWardrobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле Email должно быть не больше 100..
        /// </summary>
        public static string EmailLenghtLimit {
            get {
                return ResourceManager.GetString("EmailLenghtLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если у Вас уже есть свой сайт собственной линии одежды или Вы представитель магазина или сети магазинов, то как можно полнее заполните профиль с информацией о себе. Наши менеджеры свяжутся с Вами в кратчайшие сроки и Ваша одежда появится в наших рекомендациях..
        /// </summary>
        public static string EnterForProviders {
            get {
                return ResourceManager.GetString("EnterForProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите свой e-mail..
        /// </summary>
        public static string EnterYourEmail {
            get {
                return ResourceManager.GetString("EnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Защита глаз (от ветра и т.д.).
        /// </summary>
        public static string EYE_PROTECTION {
            get {
                return ResourceManager.GetString("EYE_PROTECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Защита лица (от ветра и т.д.).
        /// </summary>
        public static string FACE_PROTECTION {
            get {
                return ResourceManager.GetString("FACE_PROTECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ощущаемая температура.
        /// </summary>
        public static string FeelsLike {
            get {
                return ResourceManager.GetString("FeelsLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполнить.
        /// </summary>
        public static string Fill {
            get {
                return ResourceManager.GetString("Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если Вы представляете компанию и хотите публиковать одежду Вашего бренда, заполните информацию о ней.
        /// </summary>
        public static string FillCompanyInfo {
            get {
                return ResourceManager.GetString("FillCompanyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполните свой профиль чтобы получать более точные рекомендации в Вашем городе.
        /// </summary>
        public static string FillStoreProfile {
            get {
                return ResourceManager.GetString("FillStoreProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполните свой электронный гардероб, чтобы получать рекомендации по выбору своей одежды и делиться своим выбором с другими.
        /// </summary>
        public static string FillYourCloakroom {
            get {
                return ResourceManager.GetString("FillYourCloakroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле Имя должно быть не больше 50..
        /// </summary>
        public static string FirstNameLenghtLimit {
            get {
                return ResourceManager.GetString("FirstNameLenghtLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to БЕСПЛАТНО.
        /// </summary>
        public static string ForFree {
            get {
                return ResourceManager.GetString("ForFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забыли пароль?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение забытого пароля.
        /// </summary>
        public static string ForgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забыли свой пароль?.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пт.
        /// </summary>
        public static string Fri {
            get {
                return ResourceManager.GetString("Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получайте уведомления.
        /// </summary>
        public static string GetNotifications {
            get {
                return ResourceManager.GetString("GetNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получайте уведомления о возможных резких погодных изменениях..
        /// </summary>
        public static string GetNotificationsFull {
            get {
                return ResourceManager.GetString("GetNotificationsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привествуем Вас!.
        /// </summary>
        public static string HelloThere {
            get {
                return ResourceManager.GetString("HelloThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет {0}!.
        /// </summary>
        public static string HelloUserFormat {
            get {
                return ResourceManager.GetString("HelloUserFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Влажность.
        /// </summary>
        public static string Humidity {
            get {
                return ResourceManager.GetString("Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шипы.
        /// </summary>
        public static string IceProtection {
            get {
                return ResourceManager.GetString("IceProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Картинка.
        /// </summary>
        public static string ImageUrl {
            get {
                return ResourceManager.GetString("ImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В разработке.
        /// </summary>
        public static string InDevelopment {
            get {
                return ResourceManager.GetString("InDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Защита от насекомых.
        /// </summary>
        public static string INSECTS_PROTECTION {
            get {
                return ResourceManager.GetString("INSECTS_PROTECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другие пользователи могут видеть Вашу одежду в своих рекомендациях?.
        /// </summary>
        public static string IsPublic {
            get {
                return ResourceManager.GetString("IsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string ItemAdd {
            get {
                return ResourceManager.GetString("ItemAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ItemDelete {
            get {
                return ResourceManager.GetString("ItemDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string ItemDescription {
            get {
                return ResourceManager.GetString("ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детали.
        /// </summary>
        public static string ItemDetails {
            get {
                return ResourceManager.GetString("ItemDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string ItemEdit {
            get {
                return ResourceManager.GetString("ItemEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фотография.
        /// </summary>
        public static string ItemImage {
            get {
                return ResourceManager.GetString("ItemImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание (на родном языке).
        /// </summary>
        public static string ItemLocalDescription {
            get {
                return ResourceManager.GetString("ItemLocalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название (на родном языке).
        /// </summary>
        public static string ItemLocalName {
            get {
                return ResourceManager.GetString("ItemLocalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о точках продаж или филиалах.
        /// </summary>
        public static string ItemProviders {
            get {
                return ResourceManager.GetString("ItemProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нам нужна эта информация чтобы показывать Ваши точки продаж в выбранных городах..
        /// </summary>
        public static string ItemProvidersDescription {
            get {
                return ResourceManager.GetString("ItemProvidersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одежда НЕ ВИДНА больше никому.
        /// </summary>
        public static string ItIsNotPublic {
            get {
                return ResourceManager.GetString("ItIsNotPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одежда видна всем в рекомендациях.
        /// </summary>
        public static string ItIsPublic {
            get {
                return ResourceManager.GetString("ItIsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что-то пошло не так!.
        /// </summary>
        public static string JSError {
            get {
                return ResourceManager.GetString("JSError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле Фамилия должно быть не больше 50..
        /// </summary>
        public static string LastNameLenghtLimit {
            get {
                return ResourceManager.GetString("LastNameLenghtLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Узнать больше.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Защита жизни.
        /// </summary>
        public static string LIFE_PROTECTION {
            get {
                return ResourceManager.GetString("LIFE_PROTECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одежда для прохладной погоды.
        /// </summary>
        public static string LIGHT_HEAT {
            get {
                return ResourceManager.GetString("LIGHT_HEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Местоположение.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле Location должно быть не больше 100..
        /// </summary>
        public static string LocationLenghtLimit {
            get {
                return ResourceManager.GetString("LocationLenghtLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка входа.
        /// </summary>
        public static string LoginFailure {
            get {
                return ResourceManager.GetString("LoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приветствую Вас на сайте Clever Wearer!.
        /// </summary>
        public static string LoginPage {
            get {
                return ResourceManager.GetString("LoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Производитель.
        /// </summary>
        public static string MadeBy {
            get {
                return ResourceManager.GetString("MadeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основной Сайт Компании.
        /// </summary>
        public static string MainCompanyUrl {
            get {
                return ResourceManager.GetString("MainCompanyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле Основной Сайт Компании должно быть не больше 255..
        /// </summary>
        public static string MainCompanyUrlLenghtLimit {
            get {
                return ResourceManager.GetString("MainCompanyUrlLenghtLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление Вашим аккаунтом.
        /// </summary>
        public static string ManageAccount {
            get {
                return ResourceManager.GetString("ManageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление аккаунтом.
        /// </summary>
        public static string ManageAccountPage {
            get {
                return ResourceManager.GetString("ManageAccountPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление гардеробом.
        /// </summary>
        public static string ManageDressRoom {
            get {
                return ResourceManager.GetString("ManageDressRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление уведомлениями о погодных событиях.
        /// </summary>
        public static string ManageWeatherEventSubscriptions {
            get {
                return ResourceManager.GetString("ManageWeatherEventSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальный возраст.
        /// </summary>
        public static string MaxAge {
            get {
                return ResourceManager.GetString("MaxAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальный возраст.
        /// </summary>
        public static string MinAge {
            get {
                return ResourceManager.GetString("MinAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модель.
        /// </summary>
        public static string ModelBy {
            get {
                return ResourceManager.GetString("ModelBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пн.
        /// </summary>
        public static string Mon {
            get {
                return ResourceManager.GetString("Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подобрать другую одежду....
        /// </summary>
        public static string MoreButton {
            get {
                return ResourceManager.GetString("MoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ник.
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очень лёгкая одежда для идеальных условий.
        /// </summary>
        public static string NO_PROTECTION {
            get {
                return ResourceManager.GetString("NO_PROTECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К сожалению, по вашему запросу ничего не найдено. Попробуйте задать другие условия фильтра..
        /// </summary>
        public static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если вам действительно нужно больше городов в списке, скажите нам об этом: cleverwearer@gmail.com.
        /// </summary>
        public static string NoMoreCities {
            get {
                return ResourceManager.GetString("NoMoreCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы ценим Ваше время, поэтому рассылаем только уведомления о погодных изменениях. Никакого спама..
        /// </summary>
        public static string NotificationsOnly {
            get {
                return ResourceManager.GetString("NotificationsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я хочу получать уведомления о резких погодных изменениях..
        /// </summary>
        public static string NotifyMeAboutWeatherEvents {
            get {
                return ResourceManager.GetString("NotifyMeAboutWeatherEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - ИЛИ -.
        /// </summary>
        public static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы агрегируем самые интересные новости обо всём носимом и одеваемом на стыке бытового применения и мира высоких технологий. 
        ///Здесь вы найдете новости и информацию об умной одежде, часах, фитнес трекерах, умных ювелирных изделиях, трекрах здоровья и любом новейшем умном устройстве, 
        ///которое вскоре может оказаться у вас дома или быть надето на вас.
        ///
        ///К тому же, мы создаём платформу для подбора оптимальных комфортных характеристик вашей умной, или пока не очень, одежды, либо носимой электроники.
        ///С помощью  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OurGoals {
            get {
                return ResourceManager.GetString("OurGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значения в поле подтверждения пароля и в поле ввода пароля не совпадают..
        /// </summary>
        public static string PasswordCompare {
            get {
                return ResourceManager.GetString("PasswordCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен быть как минмум 6 символов..
        /// </summary>
        public static string PasswordLenghtLimit {
            get {
                return ResourceManager.GetString("PasswordLenghtLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посмотрите,что одеть для путешествия в любой город мира.
        /// </summary>
        public static string PlanTheTrip {
            get {
                return ResourceManager.GetString("PlanTheTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пожалуйста новый город.
        /// </summary>
        public static string PleaseTypeUniqueLocation {
            get {
                return ResourceManager.GetString("PleaseTypeUniqueLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название города.
        /// </summary>
        public static string PleaseTypeYourLocation {
            get {
                return ResourceManager.GetString("PleaseTypeYourLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста,подождите!.
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Давление.
        /// </summary>
        public static string Pressure {
            get {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль создан.
        /// </summary>
        public static string ProfileCreated {
            get {
                return ResourceManager.GetString("ProfileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Магазин.
        /// </summary>
        public static string ProvideBy {
            get {
                return ResourceManager.GetString("ProvideBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Защита от радиации.
        /// </summary>
        public static string RADIATION_PROTECTION {
            get {
                return ResourceManager.GetString("RADIATION_PROTECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поля ниже заполнять не обязательно, но они могут сделать Ваш профиль более красивым.
        /// </summary>
        public static string RecommendedProfileInfo {
            get {
                return ResourceManager.GetString("RecommendedProfileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Токен не совпадает или устарел..
        /// </summary>
        public static string RefreshToken {
            get {
                return ResourceManager.GetString("RefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы зарегистрированы с помощью.
        /// </summary>
        public static string RegisteredLogins {
            get {
                return ResourceManager.GetString("RegisteredLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться как новый пользователь.
        /// </summary>
        public static string RegisterNew {
            get {
                return ResourceManager.GetString("RegisterNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string RegisterPage {
            get {
                return ResourceManager.GetString("RegisterPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполните свой &lt;b&gt;{0}&lt;/b&gt;, чтобы ваш модельный ряд появился в подсказках..
        /// </summary>
        public static string RegisterShopFormat {
            get {
                return ResourceManager.GetString("RegisterShopFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить этот браузер?.
        /// </summary>
        public static string RememberBrowser {
            get {
                return ResourceManager.GetString("RememberBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помнить всегда?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На заметку!.
        /// </summary>
        public static string ReminderHeader {
            get {
                return ResourceManager.GetString("ReminderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы рекомендуем заполнить данные поля, чтобы улучшить Ваши рекомендации.
        /// </summary>
        public static string RequiredProfileInfo {
            get {
                return ResourceManager.GetString("RequiredProfileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение сброса пароля.
        /// </summary>
        public static string ResetPasswordConfirmation {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс пароля.
        /// </summary>
        public static string ResetPasswordPage {
            get {
                return ResourceManager.GetString("ResetPasswordPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбросьте Ваш пароль..
        /// </summary>
        public static string ResetYourPassword {
            get {
                return ResourceManager.GetString("ResetYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете сбросить свой пароль перейдя по &lt;a href=&apos;{0}&apos;&gt;ссылке&lt;/a&gt;..
        /// </summary>
        public static string ResetYourPasswordContent {
            get {
                return ResourceManager.GetString("ResetYourPasswordContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете сбросить свой пароль перейдя по ссылке: {0}.
        /// </summary>
        public static string ResetYourPasswordContentPlainText {
            get {
                return ResourceManager.GetString("ResetYourPasswordContentPlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс пароля на Clever Wearer.
        /// </summary>
        public static string ResetYourPasswordSubject {
            get {
                return ResourceManager.GetString("ResetYourPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сб.
        /// </summary>
        public static string Sat {
            get {
                return ResourceManager.GetString("Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите сезон.
        /// </summary>
        public static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сезон.
        /// </summary>
        public static string Seasons {
            get {
                return ResourceManager.GetString("Seasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итак, посмотрите, что мы выбрали для Вас:.
        /// </summary>
        public static string SeeResult {
            get {
                return ResourceManager.GetString("SeeResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле Selected Location должно быть не больше 100..
        /// </summary>
        public static string SelectedLocationLenghtLimit {
            get {
                return ResourceManager.GetString("SelectedLocationLenghtLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сайт Продаж.
        /// </summary>
        public static string SellCompanyUrl {
            get {
                return ResourceManager.GetString("SellCompanyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле Сайт Продаж должно быть не больше 255..
        /// </summary>
        public static string SellCompanyUrlLenghtLimit {
            get {
                return ResourceManager.GetString("SellCompanyUrlLenghtLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить новый пароль.
        /// </summary>
        public static string SendNewPassword {
            get {
                return ResourceManager.GetString("SendNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поделиться.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Делитесь со всеми.
        /// </summary>
        public static string ShareYourChoice {
            get {
                return ResourceManager.GetString("ShareYourChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Умная одежда.
        /// </summary>
        public static string SmartClothesFeed {
            get {
                return ResourceManager.GetString("SmartClothesFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новости носимых устройств.
        /// </summary>
        public static string SmartDevicesFeed {
            get {
                return ResourceManager.GetString("SmartDevicesFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новые компании.
        /// </summary>
        public static string SmartStartupsFeed {
            get {
                return ResourceManager.GetString("SmartStartupsFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Антон Ярков aka OptikLab.
        /// </summary>
        public static string SmartWearerTeam {
            get {
                return ResourceManager.GetString("SmartWearerTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор одежды произведён согласно следующим рекомендациям:.
        /// </summary>
        public static string SpecialNotes {
            get {
                return ResourceManager.GetString("SpecialNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Легкая летняя одежда.
        /// </summary>
        public static string STATIC_COOLING {
            get {
                return ResourceManager.GetString("STATIC_COOLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тёплая зимняя одежда.
        /// </summary>
        public static string STATIC_HEAT {
            get {
                return ResourceManager.GetString("STATIC_HEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы успешно Вошли под Вашим {0}-аккаунтом. Пожалуйста, подтвердите Ваш E-mail и нажмите Регистрация, чтобы выполнить вход..
        /// </summary>
        public static string SuccessfullyAuthenticatedFormat {
            get {
                return ResourceManager.GetString("SuccessfullyAuthenticatedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опишите Вашу одежду выбрав соотвествующие категории (обязательные категории помечены звёздочкой *).
        /// </summary>
        public static string SuggestionFactors {
            get {
                return ResourceManager.GetString("SuggestionFactors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что-то пошло не так.
        /// </summary>
        public static string SuggestionsError {
            get {
                return ResourceManager.GetString("SuggestionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительная защита.
        /// </summary>
        public static string SuggestionTermsAdditional {
            get {
                return ResourceManager.GetString("SuggestionTermsAdditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внешние факторы.
        /// </summary>
        public static string SuggestionTermsExtra {
            get {
                return ResourceManager.GetString("SuggestionTermsExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фактор температуры.
        /// </summary>
        public static string SuggestionTermsTemperature {
            get {
                return ResourceManager.GetString("SuggestionTermsTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вс.
        /// </summary>
        public static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Защита головы или глаз от солнца.
        /// </summary>
        public static string SUN_PROTECTION {
            get {
                return ResourceManager.GetString("SUN_PROTECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Солнцезащита.
        /// </summary>
        public static string SunProtection {
            get {
                return ResourceManager.GetString("SunProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Защита от солнца (%).
        /// </summary>
        public static string SunProtectionPercent {
            get {
                return ResourceManager.GetString("SunProtectionPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время восхода.
        /// </summary>
        public static string Sunrise {
            get {
                return ResourceManager.GetString("Sunrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время заката.
        /// </summary>
        public static string Sunset {
            get {
                return ResourceManager.GetString("Sunset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одежда для купания.
        /// </summary>
        public static string SWIMMING_TOOLS {
            get {
                return ResourceManager.GetString("SWIMMING_TOOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш профиль.
        /// </summary>
        public static string TellUs {
            get {
                return ResourceManager.GetString("TellUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо за подтверждение аккаунта. Теперь Вы можете &lt;a href=&quot;/UserProfile/Profile&quot;&gt;заполнить свой профиль и гардероб&lt;/a&gt;, чтобы носить комфортную одежду в любую погоду!.
        /// </summary>
        public static string ThankYouForConfirm {
            get {
                return ResourceManager.GetString("ThankYouForConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чт.
        /// </summary>
        public static string Thu {
            get {
                return ResourceManager.GetString("Thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Далее....
        /// </summary>
        public static string ToFullFeed {
            get {
                return ResourceManager.GetString("ToFullFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вт.
        /// </summary>
        public static string Tue {
            get {
                return ResourceManager.GetString("Tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход не выполнен..
        /// </summary>
        public static string UnsuccessfulLogin {
            get {
                return ResourceManager.GetString("UnsuccessfulLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить.
        /// </summary>
        public static string UploadButton {
            get {
                return ResourceManager.GetString("UploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле Url должно быть не больше 255..
        /// </summary>
        public static string UrlLenghtLimit {
            get {
                return ResourceManager.GetString("UrlLenghtLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти через социальные сети.
        /// </summary>
        public static string UseAnotherServiceToLogin {
            get {
                return ResourceManager.GetString("UseAnotherServiceToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to или используйте Drag&amp;Drop в область картинки.
        /// </summary>
        public static string UseDragAndDrop {
            get {
                return ResourceManager.GetString("UseDragAndDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войдите или зарегистрироваться с логином и паролем..
        /// </summary>
        public static string UseLocalAccountToLogIn {
            get {
                return ResourceManager.GetString("UseLocalAccountToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле Ник должно быть не больше 50..
        /// </summary>
        public static string UserNameLenghtLimit {
            get {
                return ResourceManager.GetString("UserNameLenghtLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле Ник является обязательным для заполнения..
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видимость.
        /// </summary>
        public static string Visibility {
            get {
                return ResourceManager.GetString("Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полные коллекции на сайте вендора.
        /// </summary>
        public static string VisitVendorButton {
            get {
                return ResourceManager.GetString("VisitVendorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Упс....
        /// </summary>
        public static string WarningHeader {
            get {
                return ResourceManager.GetString("WarningHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Защита от дождя и/или влаги.
        /// </summary>
        public static string WATER_PROTECTION {
            get {
                return ResourceManager.GetString("WATER_PROTECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Водоотталкивание.
        /// </summary>
        public static string WaterProtection {
            get {
                return ResourceManager.GetString("WaterProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Водоотталкивание (%).
        /// </summary>
        public static string WaterProtectionPercent {
            get {
                return ResourceManager.GetString("WaterProtectionPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ср.
        /// </summary>
        public static string Wed {
            get {
                return ResourceManager.GetString("Wed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вот, что ещё мы знаем о Вас..
        /// </summary>
        public static string WhatDoWeKnow {
            get {
                return ResourceManager.GetString("WhatDoWeKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что одеть через две недели.
        /// </summary>
        public static string WhatWearIn2Weeks {
            get {
                return ResourceManager.GetString("WhatWearIn2Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ежедневный прогноз.
        /// </summary>
        public static string WhatWearToday {
            get {
                return ResourceManager.GetString("WhatWearToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что одеть завтра.
        /// </summary>
        public static string WhatWearTomorrow {
            get {
                return ResourceManager.GetString("WhatWearTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восточный ветер (E).
        /// </summary>
        public static string WindE {
            get {
                return ResourceManager.GetString("WindE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восточный ветер (ENE).
        /// </summary>
        public static string WindENE {
            get {
                return ResourceManager.GetString("WindENE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восточный ветер (ESE).
        /// </summary>
        public static string WindESE {
            get {
                return ResourceManager.GetString("WindESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Северный ветер (N).
        /// </summary>
        public static string WindN {
            get {
                return ResourceManager.GetString("WindN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Северо-Восточный ветер (NE).
        /// </summary>
        public static string WindNE {
            get {
                return ResourceManager.GetString("WindNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Северный ветер (NNE).
        /// </summary>
        public static string WindNNE {
            get {
                return ResourceManager.GetString("WindNNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Северный ветер (NNW).
        /// </summary>
        public static string WindNNW {
            get {
                return ResourceManager.GetString("WindNNW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Северо-Западный ветер (NW).
        /// </summary>
        public static string WindNW {
            get {
                return ResourceManager.GetString("WindNW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Южный ветер (S).
        /// </summary>
        public static string WindS {
            get {
                return ResourceManager.GetString("WindS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юго-Восточный ветер (SE).
        /// </summary>
        public static string WindSE {
            get {
                return ResourceManager.GetString("WindSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорость ветра.
        /// </summary>
        public static string WindSpeed {
            get {
                return ResourceManager.GetString("WindSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Южный ветер (SSE).
        /// </summary>
        public static string WindSSE {
            get {
                return ResourceManager.GetString("WindSSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Южный ветер (SSW).
        /// </summary>
        public static string WindSSW {
            get {
                return ResourceManager.GetString("WindSSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юго-Западный ветер (SW).
        /// </summary>
        public static string WindSW {
            get {
                return ResourceManager.GetString("WindSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Западный ветер (W).
        /// </summary>
        public static string WindW {
            get {
                return ResourceManager.GetString("WindW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Западный ветер (WNW).
        /// </summary>
        public static string WindWNW {
            get {
                return ResourceManager.GetString("WindWNW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Западный ветер (WSW).
        /// </summary>
        public static string WindWSW {
            get {
                return ResourceManager.GetString("WindWSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Понравилось.
        /// </summary>
        public static string WishList {
            get {
                return ResourceManager.GetString("WishList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to г..
        /// </summary>
        public static string YearLabel {
            get {
                return ResourceManager.GetString("YearLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модельный год.
        /// </summary>
        public static string YearLine {
            get {
                return ResourceManager.GetString("YearLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На данный момент у вас нет пары логин-пароль к нашему сайту. Вы можете указать свой пароль, чтобы входить на сайт без внешнего поставщика. .
        /// </summary>
        public static string YouDontHaveAccount {
            get {
                return ResourceManager.GetString("YouDontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы вошли как.
        /// </summary>
        public static string YouLoggedInAs {
            get {
                return ResourceManager.GetString("YouLoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль был сброшен. Пожалуйста.
        /// </summary>
        public static string YourPasswordReset {
            get {
                return ResourceManager.GetString("YourPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы выслали инструкции для сброса пароля на ваш e-mail..
        /// </summary>
        public static string СheckEmailToResetPassword {
            get {
                return ResourceManager.GetString("СheckEmailToResetPassword", resourceCulture);
            }
        }
    }
}
